import type { InventoryItem, SystemProfile } from "./types";

export const emptyDerogation = {
  narrow_procedural_task: false,
  improves_prior_human_activity: false,
  detects_patterns_without_replacing_human: false,
  preparatory_task: false,
  performs_profiling: false,
};

export const baseProfile: SystemProfile = {
  name: "New AI system",
  description: "",
  roles: ["provider"],
  purpose: "",
  sector: "",
  is_ai_system: true,
  intended_purpose_source: "",
  eu_nexus: true,
  excluded_use_flags: [],
  placing_on_market_date: null,
  putting_into_service_date: null,
  significant_change_after_application_date: null,
  public_authority_use: false,
  deployer_public_law_body: null,
  deployer_private_public_service: null,
  provider_established_outside_eu: false,
  has_authorised_representative: null,
  substantially_modifies_system: false,
  puts_name_or_trademark_on_system: false,
  is_gpai_model: false,
  training_flops: null,
  gpai_systemic_risk_designated: false,
  prohibited_practices: [],
  annex_i_safety_component: false,
  annex_i_third_party_assessment: false,
  annex_iii_area: null,
  derogation: { ...emptyDerogation },
  interacts_with_natural_persons: false,
  generates_synthetic_content: false,
  deploys_emotion_or_biometric_categorisation: false,
  generates_deepfakes: false,
};

export const inventory: InventoryItem[] = [
  {
    id: "credit-provider",
    name: "Credit scoring provider",
    owner: "Product counsel",
    profile: {
      ...baseProfile,
      name: "CreditSightScore",
      description: "Scores consumer creditworthiness for loan origination.",
      purpose: "Consumer creditworthiness scoring",
      sector: "Financial services",
      intended_purpose_source: "Product requirements document",
      annex_iii_area: "III.5.b",
      placing_on_market_date: "2026-10-01",
    },
  },
  {
    id: "critical-infra-deployer",
    name: "Critical infrastructure deployer",
    owner: "GC review",
    profile: {
      ...baseProfile,
      name: "GridWatch",
      description: "Operational monitoring for electricity grid routing.",
      roles: ["deployer"],
      purpose: "Critical infrastructure operation support",
      sector: "Energy",
      intended_purpose_source: "Deployment runbook",
      annex_iii_area: "III.2",
      putting_into_service_date: "2027-03-15",
    },
  },
  {
    id: "gpai-systemic",
    name: "Systemic GPAI model",
    owner: "AI governance",
    profile: {
      ...baseProfile,
      name: "FoundationMax",
      description: "General-purpose model offered to downstream providers.",
      roles: ["gpai_provider"],
      purpose: "General-purpose AI model",
      sector: "AI platform",
      intended_purpose_source: "Model card",
      is_gpai_model: true,
      training_flops: 1e26,
    },
  },
  {
    id: "chatbot",
    name: "Support chatbot",
    owner: "Customer ops",
    profile: {
      ...baseProfile,
      name: "SupportDeskBot",
      description: "Customer support chatbot for first-line ticket handling.",
      purpose: "Customer support interaction",
      sector: "SaaS operations",
      intended_purpose_source: "Feature brief",
      interacts_with_natural_persons: true,
    },
  },
];
